# Generated by Django 4.2.6 on 2023-10-19 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_genre_alter_movie_options_alter_movie_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'actor',
                'ordering': ['full_name'],
            },
        ),
    ]
