# Generated by Django 4.2.6 on 2023-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_comment_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('trailer', 'trailer'), ('serial', 'serial')], default='movie', max_length=60),
        ),
    ]
