# Generated by Django 4.2.6 on 2023-10-19 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_movie_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/director')),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'director',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default=None, upload_to='images/actors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default=None, upload_to='images/movies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='base.director'),
        ),
    ]
